name: Publish to JSR

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for JSR publishing
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Verify tag matches version
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          VERSION=$(cat deno.jsonc | grep '"version"' | head -1 | cut -d '"' -f 4)
          if [ "$TAG" != "$VERSION" ]; then
            echo "Tag $TAG does not match version $VERSION in deno.jsonc"
            exit 1
          fi

      - name: Publish to JSR
        run: deno publish --allow-dirty --no-check
